app:
  log_level: "info"

ws:
  # 容器间通信用服务名直连 napcat:3001
  # NapCat(WebUI) -> 启用“WebSocket 服务端”，路径 /onebot/v11/ws，设置同一 Token
  url:   "ws://napcat:3001/onebot/v11/ws"
  token: "YOUR_TOKEN"            # 与 NapCat 面板里设置一致；若你把 token 放到 URL 上，也可留空

  heartbeat_sec: 20
  read_timeout_sec: 60
  reconnect:
    enabled: true
    max_retries: 0
    base_seconds: 1
    max_seconds: 30

store:
  path: "./data/worklog.json"
