services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    ports:
      - "3001:3001"   # OneBot WebSocket
      - "6099:6099"   # NapCat Web 管理面板
    environment:
      - TZ=${TZ}
      - NAPCAT_ACCOUNT=${QQ_ID}
    volumes:
      - ./napcat:/data
    restart: unless-stopped
