services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    ports:
      - "6099:6099"      # WebUI（首次初始化用）
      - "3001:3001"      # OneBot WS
    volumes:
      - ./napcat-data/config:/app/napcat/config
      - ./napcat-data/qq:/app/.config/QQ
    restart: unless-stopped

  wsbot:
    build:
      context: .
      dockerfile: Dockerfile      # 若你的 Go 入口不是 ./wsbot，请改这里
    depends_on:
      - napcat
    environment:
      ONEBOT_TOKEN: ${ONEBOT_TOKEN}
      ONEBOT_WS_URL: ${ONEBOT_WS_URL}   # 由 workflow 注入，值为 ws://napcat:3001/?access_token=...
      LOG_LEVEL: ${LOG_LEVEL:-info}
    restart: unless-stopped
