name: Deploy (Windows self-hosted)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  up:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh
    env:
      ONEBOT_TOKEN: ${{ secrets.ONEBOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Create .env if missing (from Secrets)
        run: |
          if (!(Test-Path ".env")) {
            if (-not $env:ONEBOT_TOKEN) { throw "Actions Secret ONEBOT_TOKEN is missing" }
            "ONEBOT_TOKEN=$env:ONEBOT_TOKEN" | Out-File -Encoding ASCII .env
            "ONEBOT_WS_URL=ws://napcat:3001/?access_token=$env:ONEBOT_TOKEN" | Add-Content -Encoding ASCII .env
            "LOG_LEVEL=info" | Add-Content -Encoding ASCII .env
          }

      - name: Docker compose up
        run: |
          docker compose pull 2>$null
          docker compose build --pull
          docker compose up -d

      - name: Show status
        run: |
          docker compose ps
          docker compose logs -n 80 --no-color || $true
