name: Deploy (Windows self-hosted)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  up:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh
    env:
      ONEBOT_TOKEN: ${{ secrets.ONEBOT_TOKEN }}  # 在仓库 Settings → Secrets 里设置
    steps:
      - uses: actions/checkout@v4

      - name: Create .env if missing (from Secrets)
        run: |
          if (!(Test-Path ".env")) {
            @"
ONEBOT_TOKEN=$env:ONEBOT_TOKEN
ONEBOT_WS_URL=ws://napcat:3001/?access_token=$env:ONEBOT_TOKEN
LOG_LEVEL=info
"@ | Out-File -Encoding ASCII .env
          }

      - name: Docker compose up
        run: |
          docker compose pull 2>$null
          docker compose build --pull
          docker compose up -d

      - name: Show status
        run: |
          docker ps
          docker compose logs -n 50 --no-color
