name: Deploy (self-hosted)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  up:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # 如果仓库里没有 .env，就用 .env.example + Secrets 生成一个
      - name: Ensure .env
        shell: bash
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi
          # 用 GitHub Secrets 覆盖 token（可选）
          if [ ! -z "${{ secrets.ONEBOT_TOKEN }}" ]; then
            sed -i.bak "s|ONEBOT_TOKEN=.*|ONEBOT_TOKEN=${{ secrets.ONEBOT_TOKEN }}|g" .env || true
          fi

      - name: Docker Compose up
        shell: bash
        run: |
          docker compose pull || true
          docker compose build --pull
          docker compose up -d

      - name: Show status
        shell: bash
        run: |
          docker ps
          docker compose logs -n 50 --no-color || true
